CREATE TABLE `papel` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(256) NOT NULL DEFAULT '0' UNIQUE,
	`normalized_name` VARCHAR(256) NOT NULL DEFAULT '' ,
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;